# Generated by Django 5.2.1 on 2025-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignscope',
            name='scope_type',
            field=models.CharField(choices=[('department', 'Department'), ('layer', 'Layer'), ('profile', 'Profile'), ('user', 'Specific User'), ('role', 'Role')], max_length=20),
        ),
    ]
