# Generated by Django 5.2.1 on 2025-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignscope_scope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='next_occurrence_date',
            field=models.DateField(blank=True, help_text='Next scheduled date for recurring campaign', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recurrence_interval',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Interval for the frequency (e.g., every 2 months if frequency is monthly and interval is 2)', null=True),
        ),
    ]
