# Generated by Django 5.2.1 on 2025-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('back_office', 'Back office'), ('front_office', 'Front office'), ('dao', 'DAO'), ('digital_team', 'Digital Team')], default='back_office', max_length=20),
        ),
    ]
