# Generated by Django 5.2.1 on 2025-05-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='access_level',
            new_name='layer',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='resource_type',
            new_name='profile',
        ),
    ]
